# Generated by Django 2.2.1 on 2020-03-08 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='contactmessage_sender_name')),
                ('content', models.TextField(blank=True, default='', help_text='message_content', null=True, verbose_name='contactmessage_content')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, verbose_name='contactmessage_sender_email')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='contactmessage_add_time')),
            ],
            options={
                'verbose_name': 'ContactMessage',
                'verbose_name_plural': 'ContactMessages',
            },
        ),
    ]
