# Generated by Django 2.2.1 on 2020-03-08 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessageinfo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time'),
        ),
        migrations.AlterField(
            model_name='contactmessageinfo',
            name='content',
            field=models.TextField(blank=True, default='', help_text='message_content', null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='contactmessageinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='sender_email'),
        ),
        migrations.AlterField(
            model_name='contactmessageinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sender_name'),
        ),
    ]
