# Generated by Django 2.2.1 on 2020-03-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmessages', '0002_auto_20200308_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessageinfo',
            name='content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='content'),
        ),
    ]
