# Generated by Django 2.2.1 on 2022-06-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmessages', '0003_auto_20200308_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessageinfo',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sender_email'),
        ),
    ]
