# Generated by Django 2.2.1 on 2019-07-24 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='program_name')),
                ('desc', models.TextField(default='', help_text='program_description', verbose_name='program_description')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='program_contact_phone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='program_contact_email')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('begin_time', models.DateTimeField(blank=True, null=True, verbose_name='program_date_time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='program_date_time')),
                ('location', models.CharField(default='', max_length=100, verbose_name='program_location')),
                ('is_completed', models.BooleanField(default=False, help_text='whether the program is completed', verbose_name='program_is_completed')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
    ]
