# Generated by Django 2.2.1 on 2019-07-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20190725_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programinfo',
            name='location',
            field=models.TextField(default='', verbose_name='program_location'),
        ),
    ]
